
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 28 13:06:01 CDT 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 20;
  public static final int Llave_c = 27;
  public static final int Op_booleano = 23;
  public static final int Llave_a = 26;
  public static final int If = 8;
  public static final int T_dato = 4;
  public static final int Else = 9;
  public static final int Corchete_c = 29;
  public static final int Corchete_a = 28;
  public static final int While = 11;
  public static final int Division = 18;
  public static final int Int = 5;
  public static final int Flotante = 34;
  public static final int Cadena = 7;
  public static final int Float = 6;
  public static final int Parentesis_c = 25;
  public static final int Parentesis_a = 24;
  public static final int For = 12;
  public static final int EOF = 0;
  public static final int P_coma = 31;
  public static final int error = 1;
  public static final int Linea = 2;
  public static final int Op_atribucion = 21;
  public static final int Print = 13;
  public static final int ERROR = 35;
  public static final int Do = 10;
  public static final int Op_logico = 19;
  public static final int Identificador = 32;
  public static final int Resta = 16;
  public static final int Multiplicacion = 17;
  public static final int Op_incremento = 22;
  public static final int Numero = 33;
  public static final int Suma = 15;
  public static final int Main = 30;
  public static final int Igual = 14;
  public static final int Comillas = 3;
}

